drop table emr.appointment;
drop table emr.barangay;
drop table emr.details;
drop table emr.infant_record;
drop table emr.med_history;
drop table emr.treat_med;
drop table emr.treat_med_record;
drop table emr.users;
drop table emr.vaccine; 